" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

" set nocompatible

set relativenumber number
syntax on
set ignorecase
" 
call plug#begin()
" 
" Language Related
Plug 'fatih/vim-go'

Plug 'airblade/vim-gitgutter'

" colorscheme
Plug 'morhetz/gruvbox'

" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'tommason14/lammps.vim'

Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

" Quality of Life plugins
Plug 'junegunn/fzf.vim'

" Interfaces
Plug 'vim-airline/vim-airline'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()
" 
" " shortcut
" " Set leader key to space
" let mapleader = " "

