add_newline = false
format = """
$username@$hostname \
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
\\$ 
"""

[username]
show_always = true
format = '$user'

[hostname]
ssh_only = false
format = '$hostname'

[directory]
style = "white"

# [character]
# success_symbol = "[%](white)"
# error_symbol = "[%](white)"
# vimcmd_symbol = "[%](white)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
