[window]
padding.x = 2
padding.y = 2
dynamic_padding = true

decorations = "buttonless"

opacity = 0.90
blur = true

[env]
term = "xterm-256color"

[font]
normal.family = "JuliaMono Nerd Font Mono"
bold.family = "JuliaMono Nerd Font Mono"
italic.family = "JuliaMono Nerd Font Mono"
bold_italic.family = "JuliaMono Nerd Font Mono"
# size = 17.0

# normal.family = "PragmataProMonoLiga Nerd Font"
# bold.family = "PragmataProMonoLiga Nerd Font"
# italic.family = "PragmataProMonoLiga Nerd Font"
# bold_italic.family = "PragmataProMonoLiga Nerd Font"
size = 15.0

[cursor]
style.blinking = "Always"

[debug]
# render_timer = true

[keyboard]
# bindings = [
#   { key = "Space", mods = "Option|Control", action = "ToggleViMode" },
#   { key = "Enter", mods = "Option", action = "ToggleSimpleFullscreen" },
# ]

[general]

live_config_reload = true

# import = ["~/.config/alacritty/themes/themes/gruvbox_material.toml"]
# import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]
