# import = ["~/alacritty-theme/themes/dracula.toml"]
# import = ["~/alacritty-theme/themes/dark"]
# import = ["~/alacritty-theme/themes/gruvbox_dark.toml"]
# import = ["~/alacritty-theme/themes/catppuccin_mocha.toml"]
import = ["~/alacritty-theme/themes/gruvbox_material_hard_dark.toml"]

live_config_reload = true

[window]
# window configuration
padding.x = 10
padding.y = 15
dynamic_padding = true

decorations = "buttonless"

opacity = 0.95
blur = true

[font]

# normal = { family = "Iosevka PragmataPro" }

normal.family = "ZedMono Nerd Font"
bold.family = "ZedMono Nerd Font"
italic.family = "ZedMono Nerd Font"
bold_italic.family = "ZedMono Nerd Font"

size = 18.0

[cursor]

style.blinking = "Always"

[debug]

# render_timer = true

[keyboard]
bindings = [
  { key = "Space", mods = "Option|Control", action = "ToggleViMode" },
  { key = "Enter", mods = "Option", action = "ToggleSimpleFullscreen" },
]
