import = ["~/alacritty-theme/themes/pastel_dark.toml"]

live_config_reload = true

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true

decorations = "buttonless"

opacity = 0.99
blur = true

[env]
term = "xterm-256color"

[font]
normal.family = "BlexMono Nerd Font Mono"
bold.family = "BlexMono Nerd Font Mono"
italic.family = "BlexMono Nerd Font Mono"
bold_italic.family = "BlexMono Nerd Font Mono"

size = 19.0

[cursor]
style.blinking = "Always"

[debug]
# render_timer = true

[keyboard]
bindings = [
  { key = "Space", mods = "Option|Control", action = "ToggleViMode" },
  { key = "Enter", mods = "Option", action = "ToggleSimpleFullscreen" },
]
