[window]
padding.x = 5
padding.y = 5
dynamic_padding = true

decorations = "full"

# opacity = 0.98
# blur = true

[env]
term = "xterm-256color"

[font]
# normal.family = "JuliaMono"
# bold.family = "JuliaMono"
# italic.family = "JuliaMono"
# bold_italic.family = "JuliaMono"
# size = 17.0

normal.family = "PragmataProMonoLiga Nerd Font"
bold.family = "PragmataProMonoLiga Nerd Font"
italic.family = "PragmataProMonoLiga Nerd Font"
bold_italic.family = "PragmataProMonoLiga Nerd Font"
size = 17.0

[cursor]
style.blinking = "Always"

[debug]
# render_timer = true

[keyboard]
# bindings = [
#   { key = "Space", mods = "Option|Control", action = "ToggleViMode" },
#   { key = "Enter", mods = "Option", action = "ToggleSimpleFullscreen" },
# ]

[general]

live_config_reload = true

# import = ["~/.config/alacritty/themes/themes/gruber_darker.toml"]
