[window]
padding.x = 5
padding.y = 5
dynamic_padding = true

decorations = "buttonless"

opacity = 0.98
blur = true

[env]
term = "xterm-256color"

[font]
normal.family = "BerkeleyMono Nerd Font Mono"
bold.family = "BerkeleyMono Nerd Font Mono"
italic.family = "BerkeleyMono Nerd Font Mono"
bold_italic.family = "BerkeleyMono Nerd Font Mono"

# normal.family = "SauceCodePro Nerd Font Mono"
# bold.family = "SauceCodePro Nerd Font Mono"
# italic.family = "SauceCodePro Nerd Font Mono"
# bold_italic.family = "SauceCodePro Nerd Font Mono"


size = 14.0

[cursor]
style.blinking = "Always"

[debug]
# render_timer = true

[keyboard]
bindings = [
  { key = "Space", mods = "Option|Control", action = "ToggleViMode" },
  { key = "Enter", mods = "Option", action = "ToggleSimpleFullscreen" },
]

[general]

live_config_reload = true

# import = ["~/alacritty-theme/themes/gruvbox_material.toml"]
import = ["~/alacritty-theme/themes/rose-pine-moon.toml"]
# import = ["~/alacritty-theme/themes/pastel_dark.toml"]
# import = ["~/alacritty-theme/themes/rose-pine.toml"]
# import = ["~/alacritty-theme/themes/rose-pine-dawn.toml"]
