# import = ["~/alacritty-theme/themes/ayu_dark.toml"]
# import = ["~/alacritty-theme/themes/base16_default_dark.toml"]

live_config_reload = true

[window]
# window configuration
padding.x = 8
padding.y = 10
dynamic_padding = true

decorations = "buttonless"

# opacity = 1
# blur = true

[font]


# normal.family = "ZedMono Nerd Font"
# bold.family = "ZedMono Nerd Font"
# italic.family = "ZedMono Nerd Font"
# bold_italic.family = "ZedMono Nerd Font"
# normal.family = "SFMono Nerd Font"
# bold.family = "SFMono Nerd Font"
# italic.family = "SFMono Nerd Font"
# bold_italic.family = "SFMono Nerd Font"

normal.family = "agave NFM"
bold.family = "agave NFM"
italic.family = "agave NFM"
bold_italic.family = "agave NFM"

size = 18.0

[cursor]

style.blinking = "Always"

[debug]

# render_timer = true

[keyboard]
bindings = [
  { key = "Space", mods = "Option|Control", action = "ToggleViMode" },
  { key = "Enter", mods = "Option", action = "ToggleSimpleFullscreen" },
]
