[tools]
java = { version = "openjdk-21" }
deno = "latest"
node = "latest"
bun = "latest"
python = "3.14.0"
zig = "0.16.0"
erlang = "latest"
elixir = "latest"
go = "1.26.2"
golangci-lint = "latest"
gofumpt = "latest"
